version: "1"

services:
  - type: web
    name: kids-quiz-web
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kids-quiz-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: MAIL_PASS
        sync: false

  - type: worker
    name: kids-quiz-index
    env: node
    buildCommand: npm install
    startCommand: node src/ai/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kids-quiz-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: MAIL_PASS
        sync: false

databases:
  - name: kids-quiz-db

